apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-local-data-grafana
  namespace: monitoring
  labels:
    type: local
    app: grafana
spec:
  storageClassName: standard
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/grafana"