image:
  repository: mhkabir/symfony-demo
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v1"

imagePullSecrets:
  - name: docker-registry-secret

appSecret:
  secret: "c29tZV9zZWN1cmVfc3RyaW5n"

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

tls:
  enabled: true
  crt: |
    -----BEGIN CERTIFICATE-----
    -----END CERTIFICATE-----
  key: |
    -----BEGIN PRIVATE KEY-----
    -----END PRIVATE KEY-----

ingress:
  enabled: true
  className: "nginx"
  tls:
    - secretName: testsecret-tls
      hosts:
        - symfony-php-demo.com
  hosts:
    - host: symfony-php-demo.com
      paths:
        - path: /
          pathType: ImplementationSpecific