apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-local-data-prometheus
  namespace: monitoring
  labels:
    app: prometheus-deployment
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi