{{- if and (.Values.tls.enabled) (not .Values.tls.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: testsecret-tls
  namespace: {{ $.Release.Namespace | quote }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.tls.crt | b64enc | quote }}
  tls.key: {{ .Values.tls.key | b64enc | quote }}
{{- end }}
